definitions:
  auth.authInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Uploads:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      filename:
        type: string
      id:
        type: integer
      updatedAt:
        type: string
      user:
        $ref: '#/definitions/models.User'
      user_id:
        type: integer
      video_id:
        type: string
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      password:
        type: string
      updatedAt:
        type: string
      uploads:
        description: One to many relationship
        items:
          $ref: '#/definitions/models.Uploads'
        type: array
      username:
        type: string
    type: object
  openai.query:
    properties:
      question:
        type: string
    type: object
  room.roomResult:
    properties:
      room_id:
        type: integer
      room_link:
        type: string
      video_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.authInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Login
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Create a user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.authInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create a user
      tags:
      - auth
  /complete:
    post:
      consumes:
      - application/json
      description: Complete file upload
      operationId: file.complete
      parameters:
      - description: file upload requirements
        in: query
        name: upload_id
        required: true
        type: string
      - description: file upload requirements
        in: query
        name: file_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "201":
          description: file saved
          schema:
            type: string
        "400":
          description: We need ID!!
          schema:
            type: object
        "404":
          description: Can not find ID
          schema:
            type: object
      security:
      - Bearer: []
      summary: Complete file upload
      tags:
      - fs
  /qa/{videoId}:
    post:
      consumes:
      - application/json
      description: Answer a question based on the video context
      parameters:
      - description: Video ID
        in: path
        name: videoId
        required: true
        type: string
      - description: Question
        in: body
        name: question
        required: true
        schema:
          $ref: '#/definitions/openai.query'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - Bearer: []
      summary: Answer a question based on the video context
      tags:
      - OpenAI
  /room/{videoId}:
    post:
      consumes:
      - application/json
      description: Create a room
      parameters:
      - description: Video ID
        in: path
        name: videoId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/room.roomResult'
      security:
      - Bearer: []
      summary: Create a room
      tags:
      - room
  /rooms:
    get:
      consumes:
      - application/json
      description: Get active rooms
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/room.roomResult'
      security:
      - Bearer: []
      summary: Get active rooms
      tags:
      - room
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload file
      operationId: file.upload
      parameters:
      - description: file upload requirements
        in: formData
        name: upload_id
        required: true
        type: string
      - description: file upload requirements
        in: formData
        name: chunk_number
        required: true
        type: integer
      - description: file upload requirements
        in: formData
        name: total_chunks
        required: true
        type: integer
      - description: file upload requirements
        in: formData
        name: total_file_size
        required: true
        type: integer
      - description: file upload requirements
        in: formData
        name: file_name
        required: true
        type: string
      - description: file upload requirements
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "201":
          description: file saved
          schema:
            type: string
        "400":
          description: We need ID!!
          schema:
            type: object
        "404":
          description: Can not find ID
          schema:
            type: object
      security:
      - Bearer: []
      summary: Upload file
      tags:
      - fs
  /uploads:
    get:
      consumes:
      - application/json
      description: Get user uploads
      operationId: user.uploads
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Uploads'
            type: array
        "400":
          description: Bad Request
          schema:
            type: object
      security:
      - Bearer: []
      summary: Get user uploads
      tags:
      - fs
  /video/{roomLink}:
    get:
      consumes:
      - application/json
      description: Serve video
      parameters:
      - description: Video ID
        in: path
        name: videoId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: file
      security:
      - Bearer: []
      summary: Serve video
      tags:
      - room
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
